version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database
    links:
      - database
    environment:
      - MONGO_HOST=database
      # do not run in production using this secret
      # docker-compose is intended to be used only for development purposes
      - JWT_SECRET="Tz7NqafQAPs4pwbhvp2w9zx7XE3smTwZ2OMA6unVs_L43QjSVY2T-xvF65w9A88FXv2GsUwJZBcPUiX0qbkkY6MDYVjS02PWd0o3OzQN_P1vFrAmcPFfzvnI9fgxVvboPwRnFCNzOACbegAN8J4FBTb0cy1r3WYUu0ZurS3nsM76h5dCdOQL97TmDsdqugRgAk16pfEna1pZ1U4HfjnKv8KebbX1qx_jYlIPJHbNDGsidLmXbTb5y4ApZQMr9w1uUyFhdRitYIlNQ2U3rFkZ6Xc1w5UPlvcL_QEnINaLwJVm-lKnPDJ67yhnRyd2uGRN0MDrfZXt8YTN2hIJ9fMoVQ"

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
